- name: Call the backend application through Skupper west
  ansible.builtin.uri:
    url: http://127.0.0.1:8080/api/hello
    method: POST
    body: '{"name": "Ansible"}'
  register: _result
  until: _result.status == 200
  retries: 10
  delay: 6
